### ISSUE TITLE
This version is no longer compatible to R 3.5.2

### ISSUE THREAD

**Issue by Saurat** [Tychobra/tychobratools#1]
![captura de pantalla 2019-02-14 a la s 22 07 07](https://user-images.githubusercontent.com/16085599/52834155-f33b5600-30a5-11e9-986d-821ae9b0b563.png)

So I tried to run the Insurance Exercice, but I couln't.

Any help?

![captura de pantalla 2019-02-14 a la s 22 20 00](https://user-images.githubusercontent.com/16085599/52834294-c5a2dc80-30a6-11e9-9320-9c901d41a6f4.png)

**Comment by merlinoa** [comment]
Thanks for checking out my example Shiny apps!  

This does not look like an issue with `tychobratools`. From your screenshots, `tychobratools` seems to have installed correctly from GitHub.  You are likely having trouble running the wc-pm-dashboard from "shiny-insurance-examples" because the "wc-pm-dashboard" Shiny app does not have the data that it needs to run locally.  Unfortunately I could not include all the data with this app for confidentiality reasons.  The table in the README to the "shiny-insurance-examples" repo shows which apps should run locally.
